# Generated by Django 2.1.2 on 2019-05-27 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('age', models.PositiveIntegerField(default=0, help_text='Edad, requerido', validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('descendant', models.CharField(blank=True, help_text='Descendencia, no requerido', max_length=200, null=True)),
                ('details', models.CharField(blank=True, help_text='Detalles, no requerido', max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('awards', models.CharField(blank=True, help_text='Premios, no requerido', max_length=200, null=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breeds.Breed')),
                ('breeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
            },
        ),
    ]
