# Generated by Django 2.1.2 on 2018-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('gender', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10)),
                ('descendant', models.CharField(blank=True, help_text='Descendencia', max_length=200, null=True)),
                ('details', models.CharField(blank=True, help_text='Detalles', max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('awards', models.CharField(blank=True, help_text='Premios', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
            },
        ),
    ]
