# Generated by Django 2.1.2 on 2019-01-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50),
        ),
    ]
