# Generated by Django 2.1.2 on 2018-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('dogs', '0003_auto_20181127_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder'),
        ),
    ]
