# Generated by Django 2.1.2 on 2018-12-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50, unique=True),
        ),
    ]
