# Generated by Django 2.1.2 on 2018-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'LikeDislike',
                'verbose_name_plural': 'LikesDislikes',
            },
        ),
    ]
