# Generated by Django 2.1.2 on 2018-11-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('likesDislikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.Actor'),
        ),
    ]
