# Generated by Django 2.1.2 on 2018-11-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20181129_2108'),
        ('likesDislikes', '0002_likedislike_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.Comment'),
        ),
    ]
