# Generated by Django 2.1.2 on 2019-05-27 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('description', models.CharField(help_text='Requerido. 200 carácteres como máximo', max_length=200)),
                ('place', models.CharField(help_text='Requerido. 100 carácteres como máximo', max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField(default=datetime.time(0, 0))),
                ('finishDate', models.DateField()),
                ('finishTime', models.TimeField(default=datetime.time(0, 0))),
                ('length', models.TimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, help_text='No requerido', null=True, upload_to='')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Association')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
