# Generated by Django 2.1.2 on 2018-11-27 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50, unique=True)),
                ('place', models.CharField(help_text='Requerido. 100 carácteres como máximo', max_length=100)),
                ('creationDate', models.DateTimeField()),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('length', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
