# Generated by Django 2.1.2 on 2018-12-09 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50, unique=True)),
                ('description', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('place', models.CharField(help_text='Requerido. 100 carácteres como máximo', max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('length', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Association')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
