# Generated by Django 2.1.2 on 2019-01-12 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(help_text='Requerido. 200 carácteres como máximo', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='length',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
