# Generated by Django 2.1.2 on 2019-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190112_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='length',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
