# Generated by Django 2.1.2 on 2018-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('events', '0002_auto_20181127_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Association'),
        ),
        migrations.AddField(
            model_name='event',
            name='breeder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder'),
        ),
    ]
