# Generated by Django 2.1.2 on 2018-11-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181129_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Association'),
        ),
        migrations.AlterField(
            model_name='event',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50),
        ),
    ]
