# Generated by Django 2.1.2 on 2019-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50),
        ),
    ]
