# Generated by Django 2.1.2 on 2019-05-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MYrequests', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='actors.Actor', verbose_name='Followed'),
        ),
        migrations.AddField(
            model_name='request',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='actors.Actor', verbose_name='Follower'),
        ),
    ]
