# Generated by Django 2.1.2 on 2019-01-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYrequests', '0002_auto_20181209_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='actors.Actor', verbose_name='Follower'),
        ),
    ]
