# Generated by Django 2.1.2 on 2019-01-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYrequests', '0003_auto_20190102_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='actors.Actor', verbose_name='Followed'),
        ),
    ]
