# Generated by Django 2.1.2 on 2019-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYrequests', '0004_auto_20190102_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='copy',
            field=models.BooleanField(default=False),
        ),
    ]
