# Generated by Django 2.1.2 on 2018-11-27 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0, max_length=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(help_text='Requerido. 200 carácteres como máximo', max_length=200)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
    ]
