# Generated by Django 2.1.2 on 2019-02-26 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_auto_20190102_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
