# Generated by Django 2.1.2 on 2018-11-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('rates', '0002_auto_20181128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.Actor'),
        ),
    ]
