# Generated by Django 2.1.2 on 2018-11-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('rates', '0004_auto_20181129_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='creator',
        ),
        migrations.AddField(
            model_name='rate',
            name='creator_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_rate', to='actors.Actor', verbose_name='Creator'),
        ),
    ]
