# Generated by Django 2.1.2 on 2019-05-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('description', models.CharField(help_text='Requerido. 200 carácteres como máximo', max_length=200)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Association')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
