# Generated by Django 2.1.2 on 2018-11-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181129_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Association'),
        ),
        migrations.AlterField(
            model_name='news',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actors.Breeder'),
        ),
    ]
