# Generated by Django 2.1.2 on 2019-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50)),
                ('text', models.CharField(help_text='Requerido. 200 carácteres como máximo', max_length=200)),
                ('copy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
