# Generated by Django 2.1.2 on 2018-11-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provinces.Province'),
        ),
        migrations.AddField(
            model_name='breeder',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='provinces.Province'),
        ),
    ]
