# Generated by Django 2.1.2 on 2018-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
        ('actors', '0002_auto_20181129_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeder',
            name='breeds',
            field=models.ManyToManyField(to='breeds.Breed'),
        ),
    ]
