# Generated by Django 2.1.2 on 2018-12-18 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20181218_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeder',
            name='cif',
        ),
        migrations.AddField(
            model_name='breeder',
            name='dni',
            field=models.CharField(default='77864314e', help_text='Requerido. 8 dígitos y una letra.', max_length=9, validators=[django.core.validators.RegexValidator(message='El formato introducido es incorrecto.', regex='^([0-9]{8})([TRWAGMYFPDXBNJZSQVHLCKE])$')], verbose_name='D.N.I.'),
            preserve_default=False,
        ),
    ]
