# Generated by Django 2.1.2 on 2018-12-18 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20181218_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeder',
            name='dni',
        ),
        migrations.AddField(
            model_name='breeder',
            name='cif',
            field=models.CharField(default='G0000000', help_text='Requerido. CIF para asociaciones. Empieza por G, seguido de 8 dígitos', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El código de identificación debe estar compuesto de 9 dígitos.', regex='^([G]{1})(\\d{8})$')], verbose_name='CIF or Center Code'),
        ),
    ]
