# Generated by Django 2.1.2 on 2018-12-01 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20181130_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='cif',
            field=models.CharField(help_text='Requerido. CIF para asociaciones. Empieza por G, seguido de 8 dígitos', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='El código de identificación debe estar compuesto de 9 dígitos.', regex='^([G]{1})(\\d{8})$')], verbose_name='CIF or Center Code'),
        ),
    ]
