# Generated by Django 2.1.2 on 2018-12-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_auto_20181201_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breeder',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
