# Generated by Django 2.1.2 on 2018-12-06 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likesDislikes', '0003_likedislike_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MYmessages', '0003_auto_20181129_2135'),
        ('comments', '0004_auto_20181129_2108'),
        ('MYrequests', '0003_auto_20181129_2135'),
        ('rates', '0005_auto_20181129_2108'),
        ('actors', '0007_auto_20181204_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
