# Generated by Django 2.1.2 on 2018-12-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_auto_20181206_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
