# Generated by Django 2.1.2 on 2019-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_association_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeder',
            name='notes',
            field=models.CharField(blank=True, help_text='No requerido. 200 carácteres como máximo.', max_length=200, null=True),
        ),
    ]
