# Generated by Django 2.1.2 on 2018-12-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0009_auto_20181206_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='closing',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='association',
            name='opening',
            field=models.TimeField(),
        ),
    ]
