# Generated by Django 2.1.2 on 2018-12-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_auto_20181206_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeder',
            name='closing',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='breeder',
            name='opening',
            field=models.TimeField(),
        ),
    ]
