# Generated by Django 2.1.2 on 2018-11-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_breeder'),
        ('actors', '0001_initial'),
        ('events', '0004_auto_20181129_2023'),
        ('news', '0003_auto_20181129_2025'),
        ('comments', '0003_comment_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='actor',
        ),
        migrations.AddField(
            model_name='comment',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.Association'),
        ),
        migrations.AddField(
            model_name='comment',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.Breeder'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_comment', to='actors.Actor', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.Dog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.News'),
        ),
    ]
