# Generated by Django 2.1.2 on 2018-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Requerido. 50 carácteres como máximo', max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('classificationFCI', models.CharField(help_text='Requerido. 100 carácteres como máximo', max_length=100)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
    ]
