# Generated by Django 2.1.2 on 2018-12-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='photo',
        ),
    ]
